[global]
disableWatchdogWarning = true

[server]
port = 8080
fileWatcherType = "none"
headless = true
maxUploadSize = 2000  # size in MB

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"